name: Deploy Streamlit App to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy via FTP (streamlit)
      run: |
        zip -r streamlit_app.zip . -x '*.git*'
        curl -X PUT -u ${{ secrets.FTP_USER }}:${{ secrets.FTP_PASSWORD }} \
          --upload-file streamlit_app.zip \
          "ftp://${{ secrets.FTP_HOST }}/site/wwwroot/streamlit_app.zip"
